artifacts_root = artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/InspectorGoole/ML-project/raw/refs/heads/main/telcom-churn.zip
  local_data_file: artifacts/data_ingestion/data.zip 
  unzip_dir: artifacts/data_ingestion 
